# ==========================================
# STAGE 1: Build React/Vite App (Gunakan versi standar, bukan alpine)
# ==========================================
FROM node:20 as build
WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# ==========================================
# STAGE 2: Serve dengan Nginx
# ==========================================
FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 8080
CMD ["nginx", "-g", "daemon off;"]