server {
    # Cloud Run secara default menggunakan port 8080
    listen 8080;
    server_name localhost;
    
    root /usr/share/nginx/html;
    index index.html;

    # Agar routing React (React Router) tidak error 404 saat di-refresh
    location / {
        try_files $uri $uri/ /index.html;
    }
}